### PR TITLE
Add shiny pokemon and palettes.

### PR DESCRIPTION
**Pull request by huderlem**
Right now, the animation that's played when a shiny pokemon enters battle is just a quick black screen flash.  I kind of want to do an actual animation.

### CODE REVIEW

**Comment by JustRegularLuna** [comment]
That sounds alright for now, but yeah an animation would be cool later on. Also, I see it is set to just show an ! ini the corner to mark them as being shiny. After I merge, I'll probably add Gen 2's shiny symbol to the font so we can use that instead, since there are plenty of unused slots in the font.

**Comment by JustRegularLuna** [comment]
Also, I see that this will shift around the map objects and scripts and things on a few routes, so I'll make a note to remind myself to tell people "Save inside a Pokemon Center to be safe" since doesn't look like the script and map data for any Pokemon centers are impacted by this, and that's easier than saying "Don't save on one of these specific seemingly random maps" haha.

**Comment by huderlem** [comment]
How committed are you to preserving people's save files?  This basically means you can't touch Bank 0 from now on if you want to preserve saves.

**Comment by JustRegularLuna** [comment]
I'm trying to be fairly committed to it for minor versions. So like, 2.1 was compatible with 2.0, and 2.2 is still compatible with both of those. But 2.0 was not even remotely compatible with 1.0, and I've already said 3.0 won't be compatible with 2.whatever saves. I'm trying to keep people from having to restart just for minor additions and bugfixes if I can help it, but for new major versions, anything goes. If that makes sense. I figured I'd really only do one more minor version in 2 before I started working on save-breaking stuff for 3 anyway though.

I was hoping to get the Battle Tower in without breaking saves, since it was just allocating unused ram and all, but if that's too much of a hassle, I'll just say "hey change of plans, Battle Tower isn't going to work the way I thought, so we're working on 3.0 now" or something.

**Comment by huderlem** [comment]
Cool, that makes sense.

**Pull request merged**
