### PR TITLE
Don't try and save an item name if dealing with a moves list.

### PR DESCRIPTION
**Pull request by huderlem**
Also delete unused function to free up bank 0 space.

### CODE REVIEW

**Comment by huderlem** [comment]
This shifts bank 0... Forgot about that.

**Comment by huderlem** [comment]
I can solve that. I'll amend this pull request.

**Comment by huderlem** [comment]
Alright, I was able to not shift any data in Bank 0.  It jumps to a previously-unused function in Bank 0, does the logic, then jumps back to the original routine.

**Comment by JustRegularLuna** [comment]
Merged, tested, seems to be working great. Thanks!

**Pull request merged**
